name: osmanalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - branca
  - contextily
  - folium
  - geopandas
  - ipywidgets
  - matplotlib
  - momepy
  - networkx
  - numpy
  - pandas
  - plotly
  - pyogrio
  - python-dateutil
  - seaborn
  - tqdm
  - xyzservices
  - ipykernel
  - jupyter_client<8
  - notebook
  - pyzmq<25
  - ipyleaflet
  - shapely
  - pip
  - pip:
      - osmnx>=2.0.0b0
      - osm2geojson
